/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ErrorImport } from './routes/error'
import { Route as RootIndexImport } from './routes/root/index'
import { Route as PagesLoginIndexImport } from './routes/pages/login/index'
import { Route as PagesHomeIndexImport } from './routes/pages/home/index'

// Create/Update Routes

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const RootIndexRoute = RootIndexImport.update({
  id: '/root/',
  path: '/root/',
  getParentRoute: () => rootRoute,
} as any)

const PagesLoginIndexRoute = PagesLoginIndexImport.update({
  id: '/pages/login/',
  path: '/pages/login/',
  getParentRoute: () => rootRoute,
} as any)

const PagesHomeIndexRoute = PagesHomeIndexImport.update({
  id: '/pages/home/',
  path: '/pages/home/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/root/': {
      id: '/root/'
      path: '/root'
      fullPath: '/root'
      preLoaderRoute: typeof RootIndexImport
      parentRoute: typeof rootRoute
    }
    '/pages/home/': {
      id: '/pages/home/'
      path: '/pages/home'
      fullPath: '/pages/home'
      preLoaderRoute: typeof PagesHomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/pages/login/': {
      id: '/pages/login/'
      path: '/pages/login'
      fullPath: '/pages/login'
      preLoaderRoute: typeof PagesLoginIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/error': typeof ErrorRoute
  '/root': typeof RootIndexRoute
  '/pages/home': typeof PagesHomeIndexRoute
  '/pages/login': typeof PagesLoginIndexRoute
}

export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/root': typeof RootIndexRoute
  '/pages/home': typeof PagesHomeIndexRoute
  '/pages/login': typeof PagesLoginIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/error': typeof ErrorRoute
  '/root/': typeof RootIndexRoute
  '/pages/home/': typeof PagesHomeIndexRoute
  '/pages/login/': typeof PagesLoginIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/error' | '/root' | '/pages/home' | '/pages/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/error' | '/root' | '/pages/home' | '/pages/login'
  id: '__root__' | '/error' | '/root/' | '/pages/home/' | '/pages/login/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ErrorRoute: typeof ErrorRoute
  RootIndexRoute: typeof RootIndexRoute
  PagesHomeIndexRoute: typeof PagesHomeIndexRoute
  PagesLoginIndexRoute: typeof PagesLoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  ErrorRoute: ErrorRoute,
  RootIndexRoute: RootIndexRoute,
  PagesHomeIndexRoute: PagesHomeIndexRoute,
  PagesLoginIndexRoute: PagesLoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/error",
        "/root/",
        "/pages/home/",
        "/pages/login/"
      ]
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/root/": {
      "filePath": "root/index.tsx"
    },
    "/pages/home/": {
      "filePath": "pages/home/index.ts"
    },
    "/pages/login/": {
      "filePath": "pages/login/index.ts"
    }
  }
}
ROUTE_MANIFEST_END */
