/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ErrorImport } from './routes/error'
import { Route as RootIndexImport } from './routes/root/index'
import { Route as PagesSignUpIndexImport } from './routes/pages/sign-up/index'
import { Route as PagesRootIndexImport } from './routes/pages/root/index'
import { Route as PagesLoginIndexImport } from './routes/pages/login/index'

// Create/Update Routes

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const RootIndexRoute = RootIndexImport.update({
  id: '/root/',
  path: '/root/',
  getParentRoute: () => rootRoute,
} as any)

const PagesSignUpIndexRoute = PagesSignUpIndexImport.update({
  id: '/pages/sign-up/',
  path: '/pages/sign-up/',
  getParentRoute: () => rootRoute,
} as any)

const PagesRootIndexRoute = PagesRootIndexImport.update({
  id: '/pages/root/',
  path: '/pages/root/',
  getParentRoute: () => rootRoute,
} as any)

const PagesLoginIndexRoute = PagesLoginIndexImport.update({
  id: '/pages/login/',
  path: '/pages/login/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/root/': {
      id: '/root/'
      path: '/root'
      fullPath: '/root'
      preLoaderRoute: typeof RootIndexImport
      parentRoute: typeof rootRoute
    }
    '/pages/login/': {
      id: '/pages/login/'
      path: '/pages/login'
      fullPath: '/pages/login'
      preLoaderRoute: typeof PagesLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/pages/root/': {
      id: '/pages/root/'
      path: '/pages/root'
      fullPath: '/pages/root'
      preLoaderRoute: typeof PagesRootIndexImport
      parentRoute: typeof rootRoute
    }
    '/pages/sign-up/': {
      id: '/pages/sign-up/'
      path: '/pages/sign-up'
      fullPath: '/pages/sign-up'
      preLoaderRoute: typeof PagesSignUpIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/error': typeof ErrorRoute
  '/root': typeof RootIndexRoute
  '/pages/login': typeof PagesLoginIndexRoute
  '/pages/root': typeof PagesRootIndexRoute
  '/pages/sign-up': typeof PagesSignUpIndexRoute
}

export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/root': typeof RootIndexRoute
  '/pages/login': typeof PagesLoginIndexRoute
  '/pages/root': typeof PagesRootIndexRoute
  '/pages/sign-up': typeof PagesSignUpIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/error': typeof ErrorRoute
  '/root/': typeof RootIndexRoute
  '/pages/login/': typeof PagesLoginIndexRoute
  '/pages/root/': typeof PagesRootIndexRoute
  '/pages/sign-up/': typeof PagesSignUpIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/error'
    | '/root'
    | '/pages/login'
    | '/pages/root'
    | '/pages/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/error' | '/root' | '/pages/login' | '/pages/root' | '/pages/sign-up'
  id:
    | '__root__'
    | '/error'
    | '/root/'
    | '/pages/login/'
    | '/pages/root/'
    | '/pages/sign-up/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ErrorRoute: typeof ErrorRoute
  RootIndexRoute: typeof RootIndexRoute
  PagesLoginIndexRoute: typeof PagesLoginIndexRoute
  PagesRootIndexRoute: typeof PagesRootIndexRoute
  PagesSignUpIndexRoute: typeof PagesSignUpIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  ErrorRoute: ErrorRoute,
  RootIndexRoute: RootIndexRoute,
  PagesLoginIndexRoute: PagesLoginIndexRoute,
  PagesRootIndexRoute: PagesRootIndexRoute,
  PagesSignUpIndexRoute: PagesSignUpIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/error",
        "/root/",
        "/pages/login/",
        "/pages/root/",
        "/pages/sign-up/"
      ]
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/root/": {
      "filePath": "root/index.tsx"
    },
    "/pages/login/": {
      "filePath": "pages/login/index.ts"
    },
    "/pages/root/": {
      "filePath": "pages/root/index.ts"
    },
    "/pages/sign-up/": {
      "filePath": "pages/sign-up/index.ts"
    }
  }
}
ROUTE_MANIFEST_END */
