export const businessActivities = [
  "Retail",
  "E-commerce",
  "Manufacturing",
  "Consulting",
  "Technology",
  "Healthcare",
  "Education",
  "Finance",
  "Real Estate",
  "Food & Beverage",
  "Transportation",
  "Construction",
  "Entertainment",
  "Marketing",
  "Legal Services",
  "Agriculture",
  "Hospitality",
  "Non-profit",
  "Other",
]
